### ISSUE TITLE
ANSI escape code and Anti-Matrix Analog Ascend

### ISSUE THREAD

**Issue by livibetter** [dhurum/mattext#4]
I've two ideas to make, but I truly don't expect them to be done since `mattext` is a simple pager.

## ANSI escape code

I was trying to run `man ../mattext.1 | ./mattext`, apparently, the escape code has no meaning to `mattext`. It properly would be an overhaul for this, but it would be nice to have it be aware of escape code, the ones for colors and effect would be sufficient.

## Anti-Matrix Analog Ascend

By design, I believe, `mattext` only does one page down, but if page up was supported, the rain will *fly* back up to the sky, wouldn't that be cool? Of course, probably not a simple task, even the animation might only need like `ascend_y = screen_height - rain_y`.

I am quite proud of myself for naming it Anti-Matrix Analog Ascend as opposite to  Matrix Digital Rain. Triple A, A as in the starting A letters or Antonyms, is that a dual triple A?

----

Note: I will close this right after opening, I don't like any issues to be hanging in Issues when I am quite certain they don't get a good chance. Same reason why I decided to only open this single issue, not need for two. It's just a short message to share my thoughts with @dhurum.

**Comment by dhurum** [comment]
Good ideas, I will try to implement them in new version

**Comment by dhurum** [comment]
Ascend animation added in 43ffe94b347a48f82d61e4106eb27145d3c2c83a

**Comment by livibetter** [comment]
@dhurum I wasn't able to compile 43ffe94 for two things:

1. GCC version, I was using 4.8.4 and it failed on `make_unique` -- "not a member of 'std'`, switching to 4.9.3 and it worked.
2. ncurses, got "not declared in this scope" error on wide char functions, such as `getcchar`, I replaced the header with `ncursesw/curses.h`.

    I don't know if it's ncurses' version or Linux distribution, I am using 5.9 on Gentoo Linux.

I think these should be added to Build section as requirements, `libev` should also be listed, since it's now required along with ncurses. C++14/1y should also be mentioned as the requirement for compiler.

**Comment by licaon-kter** [comment]
@livibetter
> ncurses, got "not declared in this scope" error on wide char functions, such as getcchar,
> I replaced the header with **ncursesw/curses.h**.

Thanks for the tip, it was failing on Debian Sid here too because of this.

**Comment by livibetter** [comment]
@licaon-kter This is weird, it is fine now without the change of ncurses header. Maybe the failure with 4.8.4 caused it, now I recall it, I didn't clean but directly made again with 4.9.3.

**Comment by licaon-kter** [comment]
Sid is on 5.2.1 already, not sure that's the problem though.

**Comment by dhurum** [comment]
I added build requirements in 654d7b5.
It is very strange that you need to add 'ncursesw' before curses include, there is a check in cmake file which should add them automatically. I checked on Debian 8 livedvd, and it worked.
But just to be sure I change order of includes in cmake as it was before my refactoring, in same commit. Can you please check?

**Comment by licaon-kter** [comment]
I'll check later, the thing is that `curses.h` was never found by **make**, although I had both [**ncourses**](https://packages.debian.org/jessie/libncurses5-dev) and [**ncoursesw**](https://packages.debian.org/jessie/libncursesw5-dev)

**Comment by livibetter** [comment]
Okay, now this really is weird. As of my previous comment, I was using 46e3c84b0e6ec28fa1873bf13c18ec2592e39788 and it made without issues after restarted the `build`. Just now, I pulled in latest 3d910f387cdf1306629db91529ec8f8bca584d87 and the exact same errors on ncurses came back when `make`, I didn't restart `build` or `make clean` first.

I `make clean`, didn't help. Then I removed `build` and restarted the build process from the beginning, it worked.

This has to do with CMake, right? (Maybe my CMake is too old, 2.8.12.2)

**Comment by licaon-kter** [comment]
In make case i guess it was user error, as I did not use the run line `mkdir build; cd build; cmake ../ && make` but I was running something like `cmake . ; make`

It works ok now, with the correct command.

**Comment by dhurum** [comment]
@livibetter You better clean all content from build directory after CMakeLists.txt was changed. `make clean` only removes what `make` produced, and cmake itself does not fully clear cache if run again - and that can lead to weird errors.
@licaon-kter In theory, it shouldn't be the problem if you run build in source dir. Maybe you did run `cmake` multiple times, installing missing libraries between them? Anyway, I am glad now all works.

**Comment by licaon-kter** [comment]
Yes, that was it and an old CmakeCache.

**Comment by livibetter** [comment]
@dhurum Thanks for the tip. I will keep that in mind next time I got strange errors.

@licaon-kter 

> In my case I guess it was user error, as I did not use the run line `mkdir build; cd build; cmake ../ && make` but I was running something like `cmake . ; make`

I was lazy even I knew I should have built with a `build`, which leading to an embarrassing #5.
