### ISSUE TITLE
Seqfault on small terminal widths

### ISSUE THREAD

**Issue by livibetter** [dhurum/mattext#8]
Using 3d910f387cdf1306629db91529ec8f8bca584d87, I noticed small terminal widths cause segmentation faults, two different cases, using `Readme.txt`:

1. Segfault when page up key is just pressed if the _width is **59** or smaller_, and there is an actual page to go back up, not on first page unless `-i` is used.
2. Segfault only after quitting if the _width is **60**_, it doesn't matter if page is changed, immediately quitting after first page is rendered can also segfault.

The terminal height doesn't seem to affect.

**Comment by dhurum** [comment]
Thank you for finding this, fixed in  71a5bc3
